# Generated by Django 4.2.3 on 2023-08-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_postmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
