# Generated by Django 4.2.3 on 2023-08-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_postmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='date',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
